const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const SECTIONS=['summary','education','experience','internships','projects','skills','certifications','awards','publications','languages','volunteer','organizations','interests','references'];
const labels=Object.fromEntries(SECTIONS.map(x=>[x,x.replace(/\b\w/g,c=>c.toUpperCase())]));
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const clone=x=>JSON.parse(JSON.stringify(x));
const baseProfile=()=>({personal:{name:'Your Name',email:'you@example.com',phone:'',location:'',website:'',linkedin:'',github:'',summary:''},sections:Object.fromEntries(SECTIONS.map(s=>[s,[]]))});
const documentFrom=(profile=baseProfile())=>({id:uid(),name:'Untitled Resume',type:'Resume',createdAt:Date.now(),updatedAt:Date.now(),profile:clone(profile),sectionOrder:SECTIONS.map(id=>({id,visible:true})),design:{template:'classic',layout:'single',accent:'#1257a6',font:'Inter',size:11,line:1.45,page:'A4',margins:'Normal',spacing:'Balanced',radius:0},versions:[]});
let state={schemaVersion:1,profile:baseProfile(),documents:[],settings:{theme:'auto',accent:'#1257a6',zoom:100},applications:[],history:[],lastDocument:null};let active=null, view='home', selectedSection=null, history=[], redo=[], saveTimer;
class Store{constructor(){this.db=null}async open(){return new Promise((ok,no)=>{let q=indexedDB.open('praxis',1);q.onupgradeneeded=()=>q.result.createObjectStore('state');q.onsuccess=()=>{this.db=q.result;ok()};q.onerror=()=>no(q.error)})}async get(){try{return await new Promise((ok,no)=>{let q=this.db.transaction('state').objectStore('state').get('app');q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)})}catch{return null}}async put(x){return new Promise((ok,no)=>{let q=this.db.transaction('state','readwrite').objectStore('state').put(x,'app');q.onsuccess=ok;q.onerror=no})}async clear(){return new Promise((ok,no)=>{let q=this.db.transaction('state','readwrite').objectStore('state').clear();q.onsuccess=ok;q.onerror=no})}}
const store=new Store();
function clean(raw){if(!raw||typeof raw!=='object')return state;let b={schemaVersion:1,profile:baseProfile(),documents:[],settings:{theme:'auto',accent:'#1257a6',zoom:100},applications:[],history:[],lastDocument:null};return {...b,...raw,profile:{...baseProfile(),...(raw.profile||{})},documents:Array.isArray(raw.documents)?raw.documents:[],applications:Array.isArray(raw.applications)?raw.applications:[]}}
function current(){return state.documents.find(d=>d.id===active)}
function esc(x=''){let d=document.createElement('div');d.textContent=String(x);return d.innerHTML}
function save(message='Saving...'){clearTimeout(saveTimer);$('#saveStatus').textContent=message;saveTimer=setTimeout(async()=>{try{state.lastDocument=active;state.settings.theme=state.settings.theme||'auto';await store.put(state);localStorage.setItem('praxis-ui',JSON.stringify(state.settings));$('#saveStatus').textContent='Saved locally ✓'}catch{$('#saveStatus').textContent='Local save failed'}},450)}
function mutate(fn,{renderView=true}={}){history.push(clone(state));if(history.length>40)history.shift();redo=[];fn();save();if(renderView)render()}
function applyTheme(){let t=state.settings.theme||'auto';document.body.className=t==='auto'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':''):t;document.documentElement.style.setProperty('--accent',state.settings.accent||'#1257a6')}
function header(title,sub=''){return `<p class="eyebrow">PRAXIS / ${sub||'CAREER DOCUMENT STUDIO'}</p><h1 class="view-title">${title}</h1>`}
function render(){applyTheme();$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));let w=$('#work');const views={home:home,profile:profileView,editor:editor,design:design,tracker:tracker,privacy:privacy,settings:settings};w.innerHTML=(views[view]||home)();wire()}
function home(){let d=state.documents;let p=state.profile;return `${header('Welcome back','DASHBOARD')}<div class="dashboard-grid grid"><div class="card"><h3>Resume Versions</h3><div class="metric">${d.length}</div></div><div class="card"><h3>Projects</h3><div class="metric">${p.sections.projects.length}</div></div><div class="card"><h3>Skills</h3><div class="metric">${p.sections.skills.length}</div></div><div class="card"><h3>Applications</h3><div class="metric">${state.applications.length}</div></div><div class="card wide"><h2>My documents</h2><div class="documents">${d.length?d.map(x=>`<div class="doc-row"><span><strong>${esc(x.name)}</strong><br><small class="muted">${esc(x.type)} · updated ${new Date(x.updatedAt).toLocaleDateString()}</small></span><span class="toolbar"><button data-open="${x.id}">Open</button><button data-duplicate="${x.id}">Duplicate</button></span></div>`).join(''):`<p class="muted">No documents yet. Create your first professional document.</p>`}</div></div><div class="card wide"><h2>PRAXIS Assistant</h2>${checks(current()||documentFrom()).slice(0,5).map(c=>`<div class="check"><span>${c.label}</span><b class="${c.ok?'status-good':'status-warn'}">${c.ok?'✓ Complete':'⚠ Review'}</b></div>`).join('')}</div></div>`}
function profileView(){return `${header('Master Profile','ONE SOURCE OF TRUTH')}<p class="muted">Information saved here can seed every new career document. Edits to an individual document remain independent.</p>${profileForm(state.profile,'master')}`}
function profileForm(p,scope){return `<div class="card" style="margin-top:18px"><h2>Personal Information</h2><div class="fields">${field('Name','name',p.personal.name)}${field('Email','email',p.personal.email,'email')}${field('Phone','phone',p.personal.phone,'tel')}${field('Location','location',p.personal.location)}${field('Website','website',p.personal.website,'url')}${field('LinkedIn','linkedin',p.personal.linkedin,'url')}${field('GitHub','github',p.personal.github,'url')}<label class="full">Professional Summary<textarea data-personal="summary" data-scope="${scope}">${esc(p.personal.summary)}</textarea></label></div><div class="toolbar" style="margin-top:12px"><button class="button primary" data-add-master="education">+ Add education</button><button class="button primary" data-add-master="experience">+ Add experience</button><button class="button primary" data-add-master="projects">+ Add project</button><button class="button primary" data-add-master="skills">+ Add skill</button></div></div><div class="card" style="margin-top:18px"><h2>Profile records</h2>${SECTIONS.filter(x=>p.sections[x].length).map(x=>`<div class="doc-row"><strong>${labels[x]}</strong><span>${p.sections[x].length} entries</span></div>`).join('')||'<p class="muted">Add education, experience, projects, or skills to build your profile.</p>'}</div>`}
function field(l,k,v,type='text'){return `<label>${l}<input type="${type}" data-personal="${k}" value="${esc(v)}"></label>`}
function editor(){let d=current();if(!d)return `<div class="card">${header('Create your first document','DOCUMENT EDITOR')}<p class="muted">Start from your Master Profile, then tailor each version for the role.</p><button class="button primary" data-command="new">Create document</button></div>`;let sec=(selectedSection&&d.sectionOrder.some(x=>x.id===selectedSection))?selectedSection:(d.sectionOrder[0]?.id||'summary');selectedSection=sec;return `<div class="editor-layout"><section class="panel form-panel"><div class="panel-head"><strong>${esc(d.name)}</strong><button data-command="rename">Rename</button></div><div class="section-list">${d.sectionOrder.map((x,i)=>`<button data-section="${x.id}" class="${x.id===sec?'active':''}"><span>${labels[x.id]||x.id}${!x.visible?' (hidden)':''}</span><small>↕</small></button>`).join('')}<button data-add-section="1">＋ Custom section</button></div><div class="form">${editSection(d,sec)}</div></section><section class="panel preview-panel"><div class="preview-actions toolbar"><button data-command="zoomout">−</button><output>${state.settings.zoom||100}%</output><button data-command="zoomin">＋</button><button data-command="fit">Fit</button><button data-command="fullscreen">Fullscreen</button><button class="button" data-command="print">Print / PDF</button></div><div class="page-wrap"><article id="printDocument" class="resume-page" style="transform:scale(${(state.settings.zoom||100)/100});transform-origin:top center;margin-bottom:${((state.settings.zoom||100)-100)*10}px">${renderDoc(d)}</article></div></section></div>`}
function editSection(d,s){let order=d.sectionOrder.find(x=>x.id===s), entries=d.profile.sections[s]||[];if(s==='summary')return `<h2>Professional Summary</h2><label>Write a concise, truthful overview of your experience.<textarea data-doc-summary="1">${esc(d.profile.personal.summary)}</textarea></label><p class="muted">Guidance: what do you do, what tools do you use, what is your contribution, and what measurable result can you truthfully describe?</p>`;return `<div class="entry-top"><h2>${labels[s]||s}</h2><span class="toolbar"><button data-toggle="${s}">${order.visible?'Hide':'Show'}</button><button data-move="up">↑</button><button data-move="down">↓</button><button data-add="${s}" class="button primary">+ Add</button></span></div>${entries.map((e,i)=>entryEditor(s,e,i)).join('')||`<p class="muted">No ${labels[s]?.toLowerCase()||s} yet. Add a record to include it in this document.</p>`}`}
function entryEditor(s,e,i){let common=`<div class="toolbar"><button data-delete-entry="${s}:${i}">Delete</button><button data-duplicate-entry="${s}:${i}">Duplicate</button></div>`;if(s==='skills'||s==='languages'||s==='interests')return `<div class="entry"><div class="entry-top"><label>Item<input data-entry="${s}:${i}:name" value="${esc(e.name||'')}"></label>${common}</div></div>`;return `<div class="entry"><div class="entry-top"><strong>${labels[s]} ${i+1}</strong>${common}</div><div class="fields">${fieldEntry('Title / Name','title',e,s,i)}${fieldEntry('Organization / Company','organization',e,s,i)}${fieldEntry('Location','location',e,s,i)}${fieldEntry('Start date','startDate',e,s,i,'month')}${fieldEntry('End date','endDate',e,s,i,'month')}<label class="full">Description / Responsibilities<textarea data-entry="${s}:${i}:description">${esc(e.description||'')}</textarea></label><label class="full">Achievements (one bullet per line)<textarea data-entry="${s}:${i}:achievements">${esc((e.achievements||[]).join('\n'))}</textarea></label><label class="full">Technologies / Tags<input data-entry="${s}:${i}:technologies" value="${esc((e.technologies||[]).join(', '))}"></label><label class="full">Link<input type="url" data-entry="${s}:${i}:url" value="${esc(e.url||'')}"></label></div></div>`}
function fieldEntry(l,k,e,s,i,type='text'){return `<label>${l}<input type="${type}" data-entry="${s}:${i}:${k}" value="${esc(e[k]||'')}"></label>`}
function renderDoc(d){let p=d.profile, visible=s=>d.sectionOrder.find(x=>x.id===s)?.visible;let contact=[p.personal.email,p.personal.phone,p.personal.location,p.personal.website,p.personal.linkedin,p.personal.github].filter(Boolean).map(esc).join(' · ');let className=d.design.layout==='two'?'two-column':d.design.layout==='left'?'sidebar-left':d.design.layout==='right'?'sidebar-right':'';let content=`<header class="resume-header"><h1>${esc(p.personal.name||'Your Name')}</h1><div class="resume-contact">${contact}</div></header>`;if(p.personal.summary&&visible('summary'))content+=`<section class="resume-section"><h2>Professional Summary</h2><p>${esc(p.personal.summary)}</p></section>`;for(let s of d.sectionOrder.map(x=>x.id).filter(x=>x!=='summary'&&visible(x))){let a=p.sections[s]||[];if(!a.length)continue;content+=`<section class="resume-section"><h2>${esc(labels[s]||s)}</h2>${a.map(e=>`<div class="resume-item"><strong>${esc(e.title||e.name||'Untitled')}</strong>${e.organization?` — ${esc(e.organization)}`:''}<span class="date">${esc([e.startDate,e.endDate].filter(Boolean).join(' – '))}</span>${e.description?`<p>${esc(e.description)}</p>`:''}${e.achievements?.length?`<ul>${e.achievements.filter(Boolean).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}${e.technologies?.length?`<p><em>${esc(e.technologies.join(' · '))}</em></p>`:''}</div>`).join('')}</section>`}return `<div class="${className}" style="--doc-accent:${esc(d.design.accent)};--doc-font:${esc(d.design.font)};--doc-size:${d.design.size}px;--doc-line:${d.design.line}">${content}</div>`}
function design(){let d=current();if(!d)return `<div class="card"><p>Create a document to use Design Studio.</p></div>`;let x=d.design;return `${header('Design Studio','DOCUMENT APPEARANCE')}<div class="design-grid grid"><div class="card"><h2>Template & Layout</h2><label>Template<select data-design="template"><option>classic</option><option>corporate</option><option>executive</option><option>minimal</option><option>software-engineer</option><option>cybersecurity</option><option>student</option><option>academic-cv</option><option>modern</option><option>portfolio</option></select></label><label>Layout<select data-design="layout"><option value="single">Single column</option><option value="two">Two column</option><option value="left">Left sidebar</option><option value="right">Right sidebar</option></select></label></div><div class="card"><h2>Typography</h2><label>Font family<select data-design="font"><option>Inter</option><option>Roboto</option><option>Lato</option><option>Source Sans 3</option><option>IBM Plex Sans</option><option>Georgia</option><option>Times New Roman</option><option>system-ui</option></select></label><label>Font size<input type="range" min="9" max="14" value="${x.size}" data-design="size"></label><label>Line height<input type="range" min="1.1" max="2" step=".05" value="${x.line}" data-design="line"></label></div><div class="card"><h2>Colors & Geometry</h2><label>Document accent<input type="color" value="${x.accent}" data-design="accent"></label><label>Corner radius<select data-design="radius"><option>0</option><option>2</option><option>4</option><option>8</option><option>12</option></select></label></div><div class="card"><h2>Page Settings</h2><label>Paper size<select data-design="page"><option>A4</option><option>Letter</option><option>Legal</option><option>Custom</option></select></label><label>Margins<select data-design="margins"><option>Compact</option><option>Normal</option><option>Wide</option><option>Custom</option></select></label><label>Spacing<select data-design="spacing"><option>Tight</option><option>Balanced</option><option>Relaxed</option><option>Custom</option></select></label></div></div>`}
function checks(d){let p=d.profile||baseProfile(), has=s=>(p.sections[s]||[]).length>0;return [{label:'Profile / contact',ok:!!(p.personal.name&&p.personal.email)},{label:'Education',ok:has('education')},{label:'Experience',ok:has('experience')||has('internships')},{label:'Projects',ok:has('projects')},{label:'Skills',ok:has('skills')},{label:'Professional summary',ok:(p.personal.summary||'').trim().length>30},{label:'Formatting',ok:!!d.design},{label:'Content density',ok:Object.values(p.sections).flat().some(x=>(x.description||'').length>30)}]}
function tracker(){return `${header('Application Tracker','LOCAL ONLY')}<div class="toolbar" style="margin:18px 0"><button class="button primary" data-add-application>+ Add application</button></div><div class="card"><div class="documents">${state.applications.map((a,i)=>`<div class="doc-row"><span><strong>${esc(a.company||'Untitled company')}</strong> — ${esc(a.role||'Role')}<br><small class="muted">${esc(a.status||'Saved')} · ${esc(a.applicationDate||'No date')}</small></span><span class="toolbar"><button data-edit-app="${i}">Edit</button><button data-delete-app="${i}">Delete</button></span></div>`).join('')||'<p class="muted">No applications yet. Track roles locally without sharing your data.</p>'}</div></div>`}
function privacy(){return `${header('Privacy Center','YOUR DATA, YOUR CONTROL')}<div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(250px,1fr));margin-top:18px"><div class="card"><h2>Local processing</h2><p>PRAXIS processes career-document data locally in this browser. No account or server is required for core functionality.</p><p class="muted">Browser storage can be cleared by browser settings; export a backup regularly.</p></div><div class="card"><h2>Backup & restore</h2><p>Backups include profiles, documents, settings, versions, and application records—never passwords or analytics data.</p><div class="toolbar"><button class="button primary" data-command="export">Export all data</button><button class="button" data-command="import">Import backup</button></div></div><div class="card"><h2>Delete local data</h2><p>This permanently removes PRAXIS data from this browser.</p><button class="button danger" data-command="wipe">Delete all local data</button></div></div>`}
function settings(){let s=state.settings;return `${header('Settings','WORKSPACE PREFERENCES')}<div class="design-grid grid"><div class="card"><h2>Interface theme</h2><label>Theme<select data-setting="theme"><option value="auto">Auto (system)</option><option value="">Light</option><option value="dark">Dark</option><option value="oled">OLED</option></select></label><label>Interface accent<input type="color" data-setting="accent" value="${s.accent||'#1257a6'}"></label></div><div class="card"><h2>Accessibility</h2><label><input type="checkbox" data-setting="contrast" ${s.contrast?'checked':''}> High contrast interface</label><p class="muted">Keyboard: Ctrl/Cmd+S save · Z undo · Y redo · P print · K commands · Esc close.</p></div><div class="card"><h2>PWA & offline</h2><p>Install this app from your browser menu. Once assets are cached, editing, preview, printing, and local data tools work offline.</p></div></div>`}
function modal(content){$('#modalRoot').innerHTML=`<div class="dialog-backdrop" role="presentation"><section class="dialog" role="dialog" aria-modal="true">${content}</section></div>`;$('[autofocus]')?.focus()};function close(){ $('#modalRoot').innerHTML=''}
function palette(){let commands=[['Create new resume','new'],['Add experience','addexp'],['Add project','addproject'],['Open Design Studio','design'],['Export PDF','print'],['Print document','print'],['Toggle dark mode','theme'],['Open Settings','settings'],['Import backup','import'],['Export backup','export'],['Open Privacy Center','privacy']];modal(`<h2>Command Palette</h2><input autofocus id="commandSearch" placeholder="Search commands…" aria-label="Search commands"><div id="commands">${commands.map(([n,c])=>`<button class="command" data-command="${c}">${n}<small class="muted"> ${c}</small></button>`).join('')}</div><p class="muted">Esc to close</p>`);$('#commandSearch').oninput=e=>$$('.command').forEach(x=>x.hidden=!x.textContent.toLowerCase().includes(e.target.value.toLowerCase()))}
function download(data,name,type='application/json'){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function addEntry(section,target=current()?.profile){let e={title:'',organization:'',location:'',startDate:'',endDate:'',description:'',achievements:[],technologies:[],url:''};if(['skills','languages','interests'].includes(section))e={name:''};target.sections[section]??=[];target.sections[section].push(e)}
function appDialog(i){let a=state.applications[i]||{company:'',role:'',location:'',applicationDate:'',status:'Saved',jobUrl:'',notes:'',interviewDate:'',followupDate:''};modal(`<h2>${i==null?'Add':'Edit'} application</h2><div class="fields">${['company','role','location','applicationDate','jobUrl','interviewDate','followupDate'].map(k=>`<label>${k.replace(/([A-Z])/g,' $1')}<input data-app-field="${k}" value="${esc(a[k]||'')}" ${k.includes('Date')?'type="date"':''}></label>`).join('')}<label>Status<select data-app-field="status">${['Saved','Applied','Interview','Offer','Rejected','Withdrawn'].map(x=>`<option ${a.status===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="full">Notes<textarea data-app-field="notes">${esc(a.notes||'')}</textarea></label></div><div class="toolbar" style="margin-top:16px"><button class="button primary" data-save-app="${i??''}">Save application</button><button class="button" data-close>Cancel</button></div>`)}
function refreshPreview(){const p=$('#printDocument');if(p&&current()){p.innerHTML=renderDoc(current());p.style.transform=`scale(${(state.settings.zoom||100)/100})`;p.style.transformOrigin='top center';}}
function wire(){
  $$('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});
  $$('[data-open]').forEach(b=>b.onclick=()=>{active=b.dataset.open;view='editor';render()});
  $$('[data-duplicate]').forEach(b=>b.onclick=()=>mutate(()=>{const d=clone(state.documents.find(x=>x.id===b.dataset.duplicate));d.id=uid();d.name+=' Copy';d.updatedAt=Date.now();state.documents.push(d);active=d.id}));
  $$('[data-personal]').forEach(i=>i.oninput=()=>{const t=i.dataset.scope==='master'?state.profile:current().profile;t.personal[i.dataset.personal]=i.value;refreshPreview();save()});
  $$('[data-add-master]').forEach(b=>b.onclick=()=>mutate(()=>{addEntry(b.dataset.addMaster,state.profile);view='profile'}));
  $('[data-section]').forEach(b=>b.onclick=()=>{selectedSection=b.dataset.section;render()});
  const custom=$('[data-add-section]');if(custom)custom.onclick=()=>{const n=prompt('Custom section name');if(n)mutate(()=>{const id=n.toLowerCase().replace(/[^a-z0-9]+/g,'-');if(!id)return;current().sectionOrder.push({id,visible:true});current().profile.sections[id]=[];selectedSection=id})};
  const summary=$('[data-doc-summary]');if(summary){const commit=e=>{if(!current())return;current().profile.personal.summary=e.target.value;current().updatedAt=Date.now();refreshPreview();save()};summary.oninput=commit;summary.onchange=commit;}
  $('[data-entry]').forEach(i=>{const commit=()=>{const [s,index,key]=i.dataset.entry.split(':');const d=current();if(!d||!d.profile.sections[s]||!d.profile.sections[s][+index])return;const e=d.profile.sections[s][+index];e[key]=key==='achievements'?i.value.split('\n'):key==='technologies'?i.value.split(',').map(x=>x.trim()).filter(Boolean):i.value;d.updatedAt=Date.now();refreshPreview();save()};i.oninput=commit;i.onchange=commit});
  $$('[data-add]').forEach(b=>b.onclick=()=>mutate(()=>addEntry(b.dataset.add)));
  $$('[data-delete-entry]').forEach(b=>b.onclick=()=>{if(confirm('Delete this entry?'))mutate(()=>{const [s,i]=b.dataset.deleteEntry.split(':');current().profile.sections[s].splice(+i,1)})});
  $$('[data-duplicate-entry]').forEach(b=>b.onclick=()=>mutate(()=>{const [s,i]=b.dataset.duplicateEntry.split(':');current().profile.sections[s].splice(+i+1,0,clone(current().profile.sections[s][+i]))}));
  const toggle=$('[data-toggle]');if(toggle)toggle.onclick=e=>mutate(()=>{const x=current().sectionOrder.find(x=>x.id===e.target.dataset.toggle);x.visible=!x.visible});
  $$('[data-move]').forEach(b=>b.onclick=()=>mutate(()=>{const d=current(),i=d.sectionOrder.findIndex(x=>x.id===selectedSection),n=b.dataset.move==='up'?i-1:i+1;if(n>=0&&n<d.sectionOrder.length){[d.sectionOrder[i],d.sectionOrder[n]]=[d.sectionOrder[n],d.sectionOrder[i]]}}));
  $('[data-design]').forEach(i=>{i.value=current()?.design[i.dataset.design]??i.value;i.oninput=()=>{const d=current();if(!d)return;const k=i.dataset.design;d.design[k]=['size','line','radius'].includes(k)?+i.value:i.value;if(k==='radius')document.documentElement.style.setProperty('--radius',i.value+'px');refreshPreview();save()}});
  $$('[data-setting]').forEach(i=>{if(i.type==='checkbox')i.checked=!!state.settings[i.dataset.setting];else i.value=state.settings[i.dataset.setting]??i.value;i.oninput=()=>mutate(()=>{state.settings[i.dataset.setting]=i.type==='checkbox'?i.checked:i.value;document.body.classList.toggle('high-contrast',!!state.settings.contrast)})});
  const addApp=$('[data-add-application]');if(addApp)addApp.onclick=()=>appDialog();
  $$('[data-edit-app]').forEach(b=>b.onclick=()=>appDialog(+b.dataset.editApp));$$('[data-delete-app]').forEach(b=>b.onclick=()=>{if(confirm('Delete application?'))mutate(()=>state.applications.splice(+b.dataset.deleteApp,1))});
  const saveApp=$('[data-save-app]');if(saveApp)saveApp.onclick=e=>{const obj={};$$('[data-app-field]').forEach(x=>obj[x.dataset.appField]=x.value);mutate(()=>{const i=e.target.dataset.saveApp;if(i==='')state.applications.push(obj);else state.applications[+i]=obj});close()};
  const closeButton=$('[data-close]');if(closeButton)closeButton.onclick=close;$$('[data-command]').forEach(b=>b.onclick=()=>command(b.dataset.command));
}
function command(c){if(c==='palette')return palette();if(c==='new')return mutate(()=>{let d=documentFrom(state.profile);state.documents.push(d);active=d.id;selectedSection='summary';view='editor'});if(c==='undo'){if(history.length){redo.push(clone(state));state=history.pop();active=state.lastDocument;selectedSection=null;render();save('Undo saved…')}return}if(c==='redo'){if(redo.length){history.push(clone(state));state=redo.pop();active=state.lastDocument;selectedSection=null;render();save('Redo saved…')}return}if(c==='theme'){mutate(()=>state.settings.theme=document.body.classList.contains('dark')?'':'dark');return}if(c==='rename'){let n=prompt('Document name',current().name);if(n)mutate(()=>current().name=n);return}if(c==='addexp'||c==='addproject'){if(!current()){command('new');return}mutate(()=>{addEntry(c==='addexp'?'experience':'projects');selectedSection=c==='addexp'?'experience':'projects';view='editor'});return}if(c==='design'||c==='settings'||c==='privacy'){view=c;render();return}if(c==='zoomout'||c==='zoomin'||c==='fit'){mutate(()=>state.settings.zoom=c==='fit'?100:Math.max(50,Math.min(150,(state.settings.zoom||100)+(c==='zoomin'?25:-25))));return}if(c==='fullscreen'){let e=$('.preview-panel');e?.requestFullscreen?.();return}if(c==='preview'){view='editor';render();setTimeout(()=>$('.preview-panel')?.scrollIntoView({behavior:'smooth'}));return}if(c==='print'){view='editor';render();setTimeout(()=>window.print(),100);return}if(c==='export'){download(JSON.stringify(state,null,2),`PRAXIS_Backup_${new Date().toISOString().slice(0,10)}.json`);return}if(c==='import'){let i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=async()=>{let f=i.files[0];if(!f||f.size>10*1024*1024)return alert('Choose a valid backup under 10 MB.');try{let raw=JSON.parse(await f.text());if(!raw||typeof raw!=='object'||(!raw.schemaVersion&&!raw.profile))throw 0;mutate(()=>{state=clean(raw);active=state.lastDocument||state.documents[0]?.id});alert('Backup restored locally.')}catch{alert('This PRAXIS backup could not be loaded. The file may be invalid or corrupted.')}};i.click();return}if(c==='wipe'){if(confirm('Delete all PRAXIS local data? This cannot be undone.')){store.clear();localStorage.removeItem('praxis-ui');state=clean();active=null;history=[];render()}return}}
async function init(){try{await store.open();state=clean(await store.get())}catch{let cached=localStorage.getItem('praxis-ui');if(cached)state.settings={...state.settings,...JSON.parse(cached)}}active=state.lastDocument||state.documents[0]?.id;applyTheme();document.body.classList.toggle('high-contrast',!!state.settings.contrast);render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});document.addEventListener('keydown',e=>{if(e.key==='Escape')close();if((e.ctrlKey||e.metaKey)&&!e.altKey){let k=e.key.toLowerCase();if(k==='s'){e.preventDefault();save()}if(k==='z'){e.preventDefault();command('undo')}if(k==='y'){e.preventDefault();command('redo')}if(k==='p'){e.preventDefault();command('print')}if(k==='k'){e.preventDefault();palette()}}})}init();
